### ISSUE TITLE
can't compile with gcc 4.2.1

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/libcperciva#248]
Attempting to compile libcperciva on OpenBSD with `make CC=gcc` produces:

```
gcc -std=c99 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -DCPUSUPPORT_CONFIG_FILE=\"cpusupport-config.h\"  -I../.. -I../../alg -I../../aws -I../../cpusupport -I../../util  -O2 -c ../../alg/sha256.c -o sha256.o
In file included from ../../alg/sha256.c:7:
../../alg/sha256_shani.h:14: error: static or type qualifiers in abstract declarator
../../alg/sha256_shani.h:15: error: static or type qualifiers in abstract declarator
../../alg/sha256.c:13: error: static or type qualifiers in abstract declarator
../../alg/sha256.c:14: error: static or type qualifiers in abstract declarator
../../alg/sha256.c:14: error: static or type qualifiers in abstract declarator
../../alg/sha256.c:15: error: static or type qualifiers in abstract declarator
*** Error 1 in tests/aws (Makefile:27 'sha256.o')
*** Error 1 in tests/aws (Makefile:16 'all')
*** Error 2 in /home/td/src/libcperciva (Makefile:39 'all')
openbsd$ gcc --version
gcc (GCC) 4.2.1 20070719 
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

openbsd$ 
```

This is an old bug in `gcc -std=c99`, which was fixed in 4.3.0 (March 5, 2008).  Unfortunately, 4.2.1 was the last version before gcc switched to GPLv3, and thus is still version that's shipped with OpenBSD.  We have no reason to care about this, as OpenBSD's cc is clang... except that autotools defaults to using gcc.  So scrypt and tarsnap will not compile "out of the box" on openbsd.

I can't think of any non-hideous programming solution, and I'm not inspired to propose a hideous solution to avoid a bug that was fixed 12 years ago but is still around due to licensing and/or ego problems.

The best approach I can think of right now is to slap a note in the `BUILDING` file of scrypt and tarsnap, warning OpenBSD people to use `configure CC=cc`.  (I suppose that I might as well warn about spiped as well, in case somebody weirdly does `make CC=gcc`.)

(BTW, I re-discover this bug once a year or so, and it takes 5-10 minutes for me to remember what's happening.  So this time, I think it's at least worth documented it in `BUILDING`.)

**Comment by cperciva** [comment]
Is this the issue where `restrict` isn't understood?  I thought we fixed that.

**Comment by gperciva** [comment]
Turns out it's even sillier than I thought.  It comes down to whether we specify a variable name in a function declaration or not.

Observe:
```
#if 0
/* This line causes the breakage. */
static int foo(int [static restrict 1]);
#else
/* This line would be ok: */
static int foo(int arr[static restrict 1]);
#endif

static int
foo(int arr[static restrict 1])
{

        return (arr[0]);
}

int
main(void)
{
        int x[1];

        x[0] = 0;
        return (foo(x));
}
```

Hmm.  We normally don't allow argument names in `.h` files, but how would you feel about
```
--- a/alg/sha256_shani.h
+++ b/alg/sha256_shani.h
@@ -11,7 +11,7 @@
  * are defined and cpusupport_x86_shani() and _ssse3() return nonzero.
  */
 void
-SHA256_Transform_shani(uint32_t[static restrict 8],
-    const uint8_t[static restrict 64]);
+SHA256_Transform_shani(uint32_t state[static restrict 8],
+    const uint8_t block[static restrict 64]);
 
 #endif /* !_SHA256_SHANI_H_ */
```

?  That, plus a similar change to `sha256.c`, are sufficient to allow compiling libcperciva with gcc 4.2.1.

(scrypt needs one extra function argument in
```
static int scryptdec_file_load_header(FILE *, uint8_t blah[static 96]);
```
and then scrypt and tarsnap can be compiled with gcc 4.2.1 as well.)

**Comment by gperciva** [comment]
(also, I assume that you'd want such a solution to be hidden with an `#ifdef POSIXFAIL_ABSTRACT_DECLARATOR` or some similar name.)

**Comment by gperciva** [comment]
Resolved in #252.
